ML_ASP/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ML_ASP.DataAccess.Repositories.IRepositories;
using ML_ASP.Models;
using ML_ASP.Models.Models;
using ML_ASP.Models.ViewModel;
using ML_ASP.Utility;
using QRCoder;
using System.Drawing;
using System.Drawing.Imaging;
using System.Net.Http;
using System.Security.Claims;
using OpenAI_API;
using ML_ASP.DTO;
using System.Web.Helpers;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Identity.UI.Services;
using System.Text.Encodings.Web;
using System.Diagnostics;
using Microsoft.AspNetCore.Hosting;
using Microsoft.ML;
using ML_net.ModelSession_3;
using Microsoft.AspNetCore.Mvc.Rendering;
using ML_ASP.Models.Models.UserDashboard;

namespace ML_ASP.Controllers
{

	public class AdminController : Controller
	{
		private readonly IUnitOfWork _unit;
		private readonly Microsoft.AspNetCore.Hosting.IWebHostEnvironment _environment;
		private readonly UserManager<Account_Model> _userManager;
		private readonly IEmailSender _emailSender;


		public SubmissionVM submissionVM { get; set; }

		public AdminController(IUnitOfWork unit,
			Microsoft.AspNetCore.Hosting.IWebHostEnvironment environment,
			UserManager<Account_Model> userManager,
			IEmailSender emailSender)
		{
			_environment = environment;
			_unit = unit;
			_userManager = userManager;
			_emailSender = emailSender;
		}

		public IActionResult Index()
		{
			return View();
		}

		[Authorize(Roles = SD.Role_Admin)]
		public IActionResult Admin()
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

			GetSubmissionVM();

			return View(submissionVM);
		}

		public IActionResult RequirementFile()
		{
			GetSubmissionVM();

			return View();
		}

		public IActionResult Overtime()
		{
			return View();
		}


		//---------------------ANALYTIC FEATURES METHODS AND GETTERS------------------------------------
		[Authorize(Roles = SD.Role_Admin)]
		public IActionResult Analytics()
		{
			var getAccounts = _unit.Account.GetAll();
			submissionVM = new SubmissionVM()
			{
				AccountList = getAccounts
			};
			return View(submissionVM);
		}

        public ActionResult ProfileFilter(string searchName)
        {
            var accounts = _unit.Account.GetAll();

            var submissionVM = new SubmissionVM()
            {
                AccountList = accounts.ToList(),
                SearchQuery = searchName
            };

            return View(nameof(Analytics), submissionVM);
        }
        // --------------------METHODS ------------------
        [Authorize(Roles = SD.Role_Admin)]
		[HttpPost]
		public IActionResult UpdateApprovalStatusBulk(List<int> id, List<string> approvalStatus, List<string> userId, List<string> originalApprovalStatus)
		{
			string newApprovalStatus = "";

			for (int i = 0; i < id.Count; i++)
			{
				if (originalApprovalStatus[i] != approvalStatus[i])
				{
					int changedId = id[i];
					newApprovalStatus = approvalStatus[i];

					_unit.Submission.ChangeApprovalStatus(changedId, newApprovalStatus);
					string fileName = _unit.Submission.GetFirstOrDefault(u => u.Id == id[i]).FileName;

					try
					{
						Notification_Model notif = new Notification_Model();
						notif.Title = "Pending Status";
						notif.Description = "Your Pending status file: " + fileName + " is changed to:" + newApprovalStatus;
						notif.NotifUserId = userId[i];

						_unit.Notification.Add(notif);

						// save changes in batch/ like dishes in restaurant
						_unit.Save();
					}
					catch (Exception ex)
					{
						string message = ex.Message;
						Console.WriteLine("Exception Message: " + message);
					}
				}
			}

			// save any remaining changes after the loop completes
			try
			{
				_unit.Save();
			}
			catch (Exception ex)
			{
				string message = ex.Message;
				Console.WriteLine("Exception Message: " + message);
			}

			return RedirectToAction(nameof(Admin));
		}

		public IActionResult UpdateOvertimeStatus(List<int> id, List<string> approvalStatus, List<string> userId, List<string> originalApprovalStatus)
		{
			string newApprovalStatus = "";

			for (int i = 0; i < id.Count; i++)
			{
				if (originalApprovalStatus[i] != approvalStatus[i])
				{
					int changedId = id[i];
					newApprovalStatus = approvalStatus[i];

					_unit.Overtime.UpdateApprovalStatus(changedId, newApprovalStatus);

					try
					{
						Notification_Model notif = new Notification_Model();
						notif.Title = "Pending Status";
						notif.Description = "Your Pending Overtime Request is changed to:" + newApprovalStatus;
						notif.NotifUserId = userId[i];

						_unit.Notification.Add(notif);

						// save changes in batch/ like dishes in restaurant
						_unit.Save();
					}
					catch (Exception ex)
					{
						string message = ex.Message;
						Console.WriteLine("Exception Message: " + message);
					}
				}
			}

			// save any remaining changes after the loop completes
			try
			{
				_unit.Save();
			}
			catch (Exception ex)
			{
				string message = ex.Message;
				Console.WriteLine("Exception Message: " + message);
			}

			return View(nameof(Overtime));
		}

		[Authorize(Roles = SD.Role_Admin)]
		[HttpPost]
		public IActionResult RequirementFileUpdate(List<string> documentId, List<string> documentVerification, List<string> documentApprovalStatus,
			List<string> id, List<string> registrationPermission, List<string> originalApprovalStatus,
			List<int> fileId, List<string> fileApprovalStatus, List<string> fileUserId, List<string> originalFileApprovalStatus)
		{
			string newApprovalStatus = "";
			string anotherNewApprovalStatus = "";
			string fileNewStatus = "";

			for (int i = 0; i < documentId.Count; i++)
			{
				if (documentApprovalStatus[i] != documentVerification[i])
				{
					anotherNewApprovalStatus = documentVerification[i];

					try
					{
						var getAcc = _unit.Account.GetFirstOrDefault(u => u.Id == documentId[i]);

						_emailSender.SendEmailAsync(getAcc.Email, "Registration Accepted", $"Congratulations your registration is completed, you can now use the dashboard in full.");

						_unit.Account.UpdateVerficationStatus(documentId[i], anotherNewApprovalStatus);

						//----for notification

						Notification_Model notif = new Notification_Model();
						notif.Title = "Pending Status";
						notif.Description = "Your Pending status for registration is changed to:" + anotherNewApprovalStatus;
						notif.NotifUserId = documentId[i];

						_unit.Notification.Add(notif);

						// save changes in batch/ like dishes in restaurant
						_unit.Save();
					}
					catch (Exception ex)
					{
						string message = ex.Message;
						Console.WriteLine("Exception Message: " + message);
					}
				}
			}

			for (int i = 0; i < id.Count; i++)
			{
				if (originalApprovalStatus[i] != registrationPermission[i])
				{
					newApprovalStatus = registrationPermission[i];

					try
					{
						var getAcc = _unit.Account.GetFirstOrDefault(u => u.Id == id[i]);

						// Synchronously call the method to change the role
						ChangeRegistrationRole(getAcc).Wait(); // Blocking call, not recommended like i did, this
															   // synchronous blocking calls, as they can lead to deadlocks if not used carefully, especially in ASP.NET Core applications

						_emailSender.SendEmailAsync(getAcc.Email, "Registration Accepted", $"Congratulations your registration is completed, you can now use the dashboard in full.");

						_unit.Account.UpdateRegistrationStatus(id[i], newApprovalStatus);

						//----for notification

						Notification_Model notif = new Notification_Model();
						notif.Title = "Pending Status";
						notif.Description = "Your Pending status for registration is changed to:" + newApprovalStatus;
						notif.NotifUserId = id[i];

						_unit.Notification.Add(notif);

						// save changes in batch/ like dishes in restaurant
						_unit.Save();
					}
					catch (Exception ex)
					{
						string message = ex.Message;
						Console.WriteLine("Exception Message: " + message);
					}
				}
			}

			for (int i = 0; i < fileId.Count; i++)
			{
				if (originalFileApprovalStatus[i] != fileApprovalStatus[i])
				{
					int changedId = fileId[i]; //the id row owner that needs change on column Approval Status
					fileNewStatus = fileApprovalStatus[i];

					try
					{
						_unit.RequirementFile.UpdateStatus(changedId, fileNewStatus);

						//----for notification
						string fileName = _unit.RequirementFile.GetFirstOrDefault(u => u.Id == fileId[i]).FileName;

						Notification_Model notif = new Notification_Model();
						notif.Title = "Pending Status";
						notif.Description = "Your Pending status file requirement: " + fileName + " is changed to:" + fileNewStatus;
						notif.NotifUserId = fileUserId[i];

						_unit.Notification.Add(notif);

						// save changes in batch/ like dishes in restaurant
						_unit.Save();
					}
					catch (Exception ex)
					{
						string message = ex.Message;
						Console.WriteLine("Exception Message: " + message);
					}
				}
			}

			// save any remaining changes after the loop completes
			try
			{
				_unit.Save();
			}
			catch (Exception ex)
			{
				string message = ex.Message;
				Console.WriteLine("Exception Message: " + message);
			}

			return RedirectToAction(nameof(RequirementFile));
		}

		//pdf viewers
		[Authorize(Roles = SD.Role_Admin)]
		public ActionResult ViewPdf(string fileName)
		{
			string path = Path.Combine(_environment.ContentRootPath + "\\Uploads", fileName);

			if (System.IO.File.Exists(path))
			{
				return File(System.IO.File.ReadAllBytes(path), "application/pdf");
			}
			else
			{
				TempData["failed"] = "File Not Found";
				return NotFound();
			}
		}

		[Authorize(Roles = SD.Role_Admin)]
		public ActionResult ViewPdf2(string id)
		{
			string path = Path.Combine(_environment.ContentRootPath + "\\Uploads", id);

			if (System.IO.File.Exists(path))
			{

ML_ASP/Controllers/TimeLogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ML_ASP.DataAccess.Repositories.IRepositories;
using ML_ASP.Models.ViewModel;
using ML_ASP.Utility;

namespace ML_ASP.Controllers
{
	public class TimeLogController : Controller
	{
		private readonly IUnitOfWork _unit;
		public SubmissionVM submissionVM { get; set; }

		public TimeLogController(IUnitOfWork unit)
        {
			_unit = unit;
        }

        public IActionResult TimeLog()
		{
			var getTimeLogs = _unit.Log.GetAll();
			submissionVM = new SubmissionVM()
			{
				LogList = getTimeLogs
			};

			return View(submissionVM);
		}

		[Authorize(Roles = SD.Role_Admin)]
		[HttpPost]
		public IActionResult UpdateApprovalStatusBulk(List<int> id, List<string> approvalStatus)
		{
			for (int i = 0; i < id.Count; i++)
			{
				int changedId = id[i];
				string newApprovalStatus = approvalStatus[i];

				_unit.Log.ChangeApprovalStatus(changedId, newApprovalStatus);
			}
			try
			{
				_unit.Save();
			}
			catch (Exception ex)
			{
				string message = ex.Message;
				Console.WriteLine("Exception Message: " + message);
			}

			return RedirectToAction(nameof(TimeLog));
		}

		#region API CALLS
		[Authorize]
		[HttpGet]
		public IActionResult GetAll()
		{
			var modelList = _unit.Log.GetAll();
			return Json(new { data = modelList });
		}

		#endregion
	}
}

ML_ASP/Views/TimeLog/TimeLog.cshtml
@model ML_ASP.Models.ViewModel.SubmissionVM
@{
	Layout = "_AMasterPage_2_1";
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Boxicons -->
	<link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
	<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
	<link href="//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" rel="stylesheet" />
	<!-- popup modal -->
	<!-- My CSS -->
	<link rel="stylesheet" href="~/css/adminStyle.css">
	<title>AdminHub</title>
</head>
<body>


	<!-- SIDEBAR -->
	<section id="sidebar">
		<a href="#" class="brand">
			<i class='bx bxs-smile'></i>
			<span class="text">AdminHub</span>
		</a>
		<ul class="side-menu top">
			<li>
				<a asp-controller="Admin" asp-action="Admin">
					<i class='bx bxs-dashboard'></i>
					<span class="text">Dashboard</span>
				</a>
			</li>
			<li>
				<a asp-controller="Admin" asp-action="Analytics">
					<i class='bx bxs-doughnut-chart'></i>
					<span class="text">Analytics</span>
				</a>
			</li>
			<li class="active">
				<a asp-controller="TimeLog" asp-action="TimeLog">
					<i class='bx bxs-spreadsheet'></i>
					<span class="text">Time Log</span>
				</a>
			</li>
			<li>
				<a asp-controller="Admin" asp-action="RequirementFile">
					<i class='bx bxs-file-pdf'></i>
					<span class="text">Registration Files</span>
				</a>
			</li>
			<li>
				<a asp-controller="Admin" asp-action="Overtime">
					<i class='bx bxs-time-five'></i>
					<span class="text">Overtime Requests</span>
				</a>
			</li>
		</ul>
		<ul class="side-menu">
			<!--<li>
				<a href="#" class="logout">
					<i class='bx bxs-log-out-circle'></i>
					<span class="text">Logout</span>
				</a>
			</li>-->
		</ul>
	</section>
	<!-- SIDEBAR ENDS -->

	<!-- CONTENT -->
	<section id="content">
		<!-- NAVBAR -->
		<nav>
			<i class='bx bx-menu'></i>
			<div id="noti_Container">
				<span class="material-icons-sharp">
					notifications_none
				</span>
			</div>
			<a href="#" class="nav-link">Categories</a>
		</nav>
		<!-- NAVBAR -->
		<!-- MAIN -->
		<main>
			<div class="head-title">
				<div class="left">
					<h1>Time Log</h1>
					<ul class="breadcrumb">
						<li>
							<a href="#">Time Log</a>
						</li>
						<li><i class='bx bx-chevron-right'></i></li>
						<li>
							<a class="active" href="#">Home</a>
						</li>
					</ul>
				</div>
			</div>
			<!-- SOME NEW FEATURE FOR TIME LOGS-->
			<div>
				<h1 class="heading"> Time Log </h1>
				<h3 class="title"> Approval and Updates </h3>
				<form id="approvalForm" asp-controller="TimeLog" asp-action="UpdateApprovalStatusBulk" method="post">
					<table id="timeTable">
						<thead>
							<tr>
								<th>Name</th>
								<th>Date Time</th>
								<th>Time Log</th>
								<th>Approval Status</th>
								<th>Model Approval</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
					<button id="updateButton" type="button">Update Approval Status</button>
				</form>
			</div>
			<!-- SOME NEW FEATURE FOR TIME LOGS ENDS-->
		</main>
		<!-- MAIN -->
	</section>
	<!-- CONTENT -->
</body>
</html>
@section Scripts{
	@{
		<script src="~/js/timeLog/timelog.js"></script>
		<script src="~/js/adminScript.js"></script>
	}
	<script>
		document.getElementById('updateButton').addEventListener('click', function () {
			confirmInput();
		});

		function confirmInput() {
			Swal.fire({
				title: "Are you sure?",
				text: "You made changes!",
				icon: "warning",
				showCancelButton: true,
				confirmButtonColor: "#3085d6",
				cancelButtonColor: "#d33",
				confirmButtonText: "Yes, change it!"
			}).then((result) => {
				if (result.isConfirmed) {
					document.getElementById('approvalForm').submit();
				}
			});
		}
	</script>
}