ML_ASP/Controllers/FileManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.ML;
using ML_ASP.DataAccess.Repositories.IRepositories;
using ML_ASP.Models;
using ML_ASP.Models.Models;
using ML_ASP.Models.ViewModel;
//using ML_net.ModelSession_1;
using ML_net.ModelSession_2;
using System.Security.Claims;
using ML_ASP.Utility;
using ML_net.ModelSession_3;
using Azure.Storage.Files.Shares;
using ML_net;

namespace ML_ASP.Controllers
{
    public class FileManagementController : Controller
    {
        private readonly IUnitOfWork _unit;
        private readonly MLContext _context;
        private readonly PredictionEngine<Object_DataSet, Prediction> _predictionEngine;
        private PredictionEngine<Image_DataSet, ImagePrediction> _imagClassificationEngine;
        private readonly Microsoft.AspNetCore.Hosting.IWebHostEnvironment _environment;

        public SubmissionVM submissionVM { get; set; }


        //constructor for every model and object needed
        public FileManagementController(Microsoft.AspNetCore.Hosting.IWebHostEnvironment environment,
            IUnitOfWork unit,
            MLContext context)
        {
            _unit = unit;
            _environment = environment;
            _context = context; //was supposed to be DB, but the architecture was applied late

            //var currentDirectory = _environment.ContentRootPath;


            //===================--------------------------------
        }

        public static string GetAssetsPath(string relativePath)
        {
            // Get the physical path of the directory containing the web application
            string appDirectory = AppDomain.CurrentDomain.BaseDirectory;

            // Combine the application directory with the relative path to the assets directory
            string assetsPath = Path.Combine(appDirectory, relativePath);

            return assetsPath;
        }


        [Authorize(Roles = SD.Role_User)]
        public IActionResult FileManagement()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var workloadsubmissionlist = _unit.WorkloadSubmissionList.GetAll(i => i.SubmissionUserID == claim.Value);//to get the list of all workloads of current user 

            //populate the reminderlist 
            submissionVM = new SubmissionVM()
            {
                ReminderList = _unit.Reminder.GetAll(u => u.UserId == claim.Value),
                WorkloadList = _unit.Workload.GetAll(),
                CurrentUserSubmissionList = workloadsubmissionlist,
                WorkloadSubmissionList = _unit.WorkloadSubmissionList.GetAll(),
            };

            //pass in the current user Profile Image Url
            if (claim != null)
            {
                var getAcc = _unit.Account.GetFirstOrDefault(x => x.Id == claim.Value);
                string? imageUrl = getAcc.ImageUrl;

                ViewData["ImageUrl"] = imageUrl;

                return View(submissionVM);
            }
            else
            {
                return View(submissionVM);
            }
        }

        [HttpPost]
        public ActionResult DeleteFile(int id, string fileName)
        {
            var killFile = _unit.Submission.GetFirstOrDefault(u => u.Id == id);
            _unit.Submission.Remove(killFile);
            _unit.Save();

            string path = Path.Combine(_environment.ContentRootPath + "\\Uploads", fileName);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }

            TempData["failed"] = "File Deleted";

            return RedirectToAction(nameof(FileManagement));
        }

        public ActionResult DeleteFileImage(int id, string fileName)
        {
            var killFile = _unit.Log.GetFirstOrDefault(u => u.Id == id);
            _unit.Log.Remove(killFile);
            _unit.Save();
            string path = Path.Combine(_environment.ContentRootPath + "\\Uploads", fileName);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }

            TempData["failed"] = "File Deleted";

            return RedirectToAction(nameof(FileManagement));
        }

        [Authorize(Roles = SD.Role_User)]
        [HttpPost]
        public IActionResult FileManagement(List<IFormFile> postedFiles, int modelId, DateTime dueDate)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            // --UPLOADING FILE --
            string uploadFolderName = "Uploads";
            string submissionFolderName = "Submission";
            string projectPath = _environment.ContentRootPath;
            string uploadPath = Path.Combine(projectPath, uploadFolderName);
            string submissionPath = uploadPath; // Default to the Uploads folder

            Random rnd = new Random();
            int num = rnd.Next(80, 90);

            Prediction prediction = null;

            if (!Directory.Exists(uploadPath))
            {
                Directory.CreateDirectory(uploadPath);
            }

            bool submissionIsGreaterThan1 = false;

            if (postedFiles.Count > 1)
            {
                submissionIsGreaterThan1 = true;
                submissionPath = Path.Combine(uploadPath, submissionFolderName);

                if (!Directory.Exists(submissionPath))
                {
                    Directory.CreateDirectory(submissionPath);
                }
                else
                {
                    // If "Submission" folder already exists, find the next available name
                    int attempt = 1;
                    while (Directory.Exists(submissionPath))
                    {
                        submissionFolderName = $"Submission_{attempt}";
                        submissionPath = Path.Combine(uploadPath, submissionFolderName);
                        attempt++;
                    }

                    Directory.CreateDirectory(submissionPath);
                }
            }

            //UPLOADING FILES STARTS---------------
            List<string> uploadedFiles = new List<string>();
            foreach (IFormFile postedFile in postedFiles)
            {
                var submissionModel = new SubmissionModel();
                string fileName = Path.GetFileName(postedFile.FileName);
                string filePath = Path.Combine(submissionPath, fileName);

                int attempt = 1;
                while (System.IO.File.Exists(filePath))
                {
                    // Handle file name conflict as needed
                    string extension = Path.GetExtension(fileName);
                    string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(fileName);
                    fileName = $"{fileNameWithoutExtension}_{attempt}{extension}";
                    filePath = Path.Combine(submissionPath, fileName);
                    attempt++;
                }

                using (FileStream stream = new FileStream(filePath, FileMode.Create))
                {
                    postedFile.CopyTo(stream);
                    uploadedFiles.Add(fileName);
                    ViewBag.Message += string.Format("<b>{0}</b> uploaded.<br />", fileName);
                }

                int numWordsInPdf = ML_net.ModelSession_2.Demo.CountSpacesInPdf(filePath);

                var new_data = new Object_DataSet
                {
                    NumberOfWords = numWordsInPdf,
                    Grade = num
                };

                //prediction = _predictionEngine.Predict(new_data);
                int convertPrediction = 0;

                //determine the additional grade based on how many days have passed
                DateTime currentDate = DateTime.Now;
                DateTime earlySubmittedDate = dueDate.AddDays(-3);
                if (currentDate < dueDate) // Submission is before the due date
                {
                    convertPrediction += 4;
                }
                else if (currentDate <= earlySubmittedDate) // Submission is on time (within 3 days after due date)
                {
                    convertPrediction += 3;
                }
                else // Submission is late
                {
                }

                string predGrade = convertPrediction.ToString("F2");

                //adding identity for the one who upload the file
                submissionModel.SubmissionUserId = claim.Value;

                //adding folderid if 1 or more files is updated
                if (postedFiles.Count > 1)
                {
                    var fileModel = SubmissionInjection(submissionModel, fileName, predGrade, submissionFolderName, submissionIsGreaterThan1);
                    

                    _unit.Submission.Add(fileModel);
                    _unit.Save();
                }
                else
                {
                    var fileModel = SubmissionInjection(submissionModel, fileName, predGrade, submissionIsGreaterThan1);

                    _unit.Submission.Add(fileModel);
                    
                    _unit.Save();
                }
            }
            //UPLOADING FILES ENDS-------------
            if (postedFiles.Count <= 0)
            {
                TempData["failed"] = "No File was Uploaded";

                return RedirectToAction(nameof(FileManagement));
            }
            //VERIFICATION OF NO UPLOAD SUBMIT ENDS--------------

            //DATABASE COLLERATION ENDS------------

            TempData["success"] = "Uploaded Succesfully!";

            if (claim != null)
            {
                var getAcc = _unit.Account.GetFirstOrDefault(x => x.Id == claim.Value);
                string? imageUrl = getAcc.ImageUrl;

ML_ASP/Controllers/NotificationController.cs
using Microsoft.AspNetCore.Mvc;
using ML_ASP.DataAccess.Repositories.IRepositories;
using System.Security.Claims;

namespace ML_ASP.Controllers
{
    public class NotificationController : Controller
    {
        private readonly IUnitOfWork _unit;
        public NotificationController(IUnitOfWork unit)
        {
            _unit = unit;
        }

        public IActionResult Index()
        {
            return View();
        }

        #region API CALLS
        [HttpGet]
        public ActionResult GetAllNotification()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string id = claim.Value;

            var sublist = _unit.Notification
                  .GetAll(u => u.NotifUserId == id)
                  .ToList();

            return Json(new { data = sublist});
        }
        #endregion
    }
}

ML_ASP/Views/Shared/_AMasterPage_1.cshtml
@using Microsoft.AspNetCore.Identity
@using ML_ASP.Utility

@inject SignInManager<Account_Model> SignInManager
@inject UserManager<Account_Model> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ML_ASP</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: antiquewhite">
            <a>
                <ul class="navbar-nav">
                    <li class="nav-item">
                <img style="margin-left: 2rem; width: 9rem; height:auto" class="logo" src="~/assets/dashboard/logo-no-background.png" />
                    </li>
                </ul>
            </a>

            <hr class="vertical-line">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                    @if (SignInManager.IsSignedIn(User))
                    {
                            var currentUser = await UserManager.GetUserAsync(User);
                            var isAdmin = await UserManager.IsInRoleAsync(currentUser, SD.Role_Admin);
                            if (await UserManager.IsInRoleAsync(currentUser, SD.Role_Admin))
                            {
                                <a class="nav-link text-dark" asp-action="Admin" asp-controller="Admin">
                                    <span class="material-symbols-outlined">
                                        dashboard
                                    </span>
                                    Admin Dashboard
                                </a>
                            }

                            if (await UserManager.IsInRoleAsync(currentUser, SD.Role_User))
                            {
                                <a class="nav-link text-dark" asp-action="Dashboard" asp-controller="Dashboard">
                                    <span class="material-symbols-outlined">
                                        dashboard
                                    </span>
                                    Trainee Dashboard
                                </a>
                            }

                            if (await UserManager.IsInRoleAsync(currentUser, SD.Role_Unregistered))
                            {
                                <a class="nav-link text-dark" asp-action="Index" asp-controller="RequirementFile">

                                    @if (currentUser.DocumentVerification == "Approved" && !isAdmin)
                                    {
                                        <span class="material-symbols-outlined">
                                            dashboard
                                        </span>
                                        <h2>Requirement Form</h2>
                                    }
                                </a>
                            }
                            

                        }
                    else
                    {
                        <a class="nav-link text-dark d-flex align-items-center" asp-action="Index" asp-controller="Home">
                            <span class="material-symbols-outlined me-2">
                                home
                            </span>
                            Home
                        </a>
                    }
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <partial name="_LoginPartial" />
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/rowgroup/1.1.4/js/dataTables.rowGroup.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<style>
    .vertical-line {
        display: none;
        height: 40px;
        width: 0;
        border: 1px solid black;
        margin: 0;
        margin-left: 1rem;
        margin-right: 1rem;
        transform: rotate(180deg);
    }

    @@media (min-width: 768px) {
        .vertical-line {
            display: block; /* Show the vertical line on desktop */
        }
    }
</style>

ML_ASP/Views/Shared/_AMasterPage_2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ML_ASP</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/ML_ASP.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/rowgroup/1.1.4/js/dataTables.rowGroup.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Styles", required: false)
</body>
</html>

ML_ASP/Views/Shared/_AMasterPage_2_1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ML_ASP</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/ML_ASP.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/js/notification/ikr.notification.css">
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    <script src="~/js/notification/ikr.notificationPlugin.js"> </script>

    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/rowgroup/1.1.4/js/dataTables.rowGroup.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#noti_Container").ikrNotificationSetup();
            $.ajax({
                url: "/Notification/GetAllNotification",
                type: "GET",
                dataType: "json",
                traditional: true,
                contentType: "application/json;charset=utf-8",
                success: function (data) {
                    var notifications = data;
                    $("#noti_Container").ikrNotificationCount({
                        NotificationList: notifications.data,
                        ListTitlePropName: "title",
                        ListBodyPropName: "description",
                        ControllerName: "Notification",
                        ActionName: "GetAllNotification"
                    });
                },
                error: function (xhr, status, error) {
                }
            });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Styles", required: false)
</body>
</html>

ML_ASP/Views/Shared/_AMasterPage_3.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ML_ASP</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/js/notification/ikr.notification.css">
    <link href="//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: antiquewhite">
            <a asp-controller="Home" asp-action="Index">
                <img class="logo" src="~/assets/dashboard/logo-no-background.png" />
            </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse justify-content-end">
                    <ul class="navbar-nav">
                        @* for filemanagement *@
                        <li class="nav-item d-sm-none">
                            <a class="nav-link text-dark text-sm" asp-controller="FileManagement" asp-action="FileManagement">
                                <span class="material-symbols-outlined">
                                    dashboard
                                </span>
                                File Management
                            </a>
                        </li>
                        @* for dashboard *@
                        <li class="nav-item d-sm-none">
                            <a class="nav-link text-dark text-sm" asp-controller="Dashboard" asp-action="Dashboard">
                                <span class="material-symbols-outlined">
                                    dashboard
                                </span>
                                Dashboard
                            </a>
                        </li>
                        <li class="nav-item">
                            <div id="noti_Container">
                                <span class="material-icons-sharp" style="position: relative; top:10px; right: 10px;">
                                    notifications_none
                                </span>
                            </div>
                        </li>
                        <li class="nav-item">
                            <partial name="_LoginPartial" />
                        </li>
                    </ul>
                </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    <script src="~/js/notification/ikr.notificationPlugin.js"> </script>

    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/rowgroup/1.1.4/js/dataTables.rowGroup.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#noti_Container").ikrNotificationSetup();
            $.ajax({
                url: "/Notification/GetAllNotification",
                type: "GET",
                dataType: "json",
                traditional: true,
                contentType: "application/json;charset=utf-8",
                success: function (data) {
                    var notifications = data;
                    $("#noti_Container").ikrNotificationCount({
                        NotificationList: notifications.data,
                        ListTitlePropName: "title",
                        ListBodyPropName: "description",
                        ControllerName: "Notification",
                        ActionName: "GetAllNotification"
                    });
                },
                error: function (xhr, status, error) {
                }
            });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ML_ASP/Views/Shared/_CustomPopup.cshtml
@* partial view for popups *@

<form method="post" asp-action="AddOvertimeRequest" asp-controller="Dashboard" enctype="multipart/form-data">
<div id="popup" class="popup-overlay">
    <div class="popup-content">
        <span class="close-btn">&times;</span>
        <h2>Request Overtime</h2>

        <label for="description">Overtime Description:</label>
        <textarea id="description" name="description" placeholder="Provide description on overtime, and reason."></textarea>

        <label>
                <input type="checkbox" id="daysOvertimeCheckbox"> Days Overtime
        </label>

        <div id="datePickers" style="display: none;">
            <label for="startDate">Start Date:</label>
            <input type="date" id="startDate" name="startDate">
            <br>
            <label for="endDate">End Date:</label>
            <input type="date" id="endDate" name="endDate">
        </div>

        <div id="datePickers2">
            <label for="overtimeDate">Overtime Date:</label>
            <input type="date" id="overtimeDate" name="overtimeDate" required>
        </div>

        <label for="endTime">Select Request End Time:</label>
        <input type="time" id="endTime" name="endTime" style="margin-bottom:2rem;" required>
        <br />

        <label for="attachDocumentButton">Attach Request Letter</label>
        <a asp-action="EditTemplate" asp-controller="Dashboard">Edit Template</a>
        
        <div style="margin-top:10px;" class="prediction" style="margin-bottom: 20px;">
                <input type="file" id="attachDocumentButton" name="postedFiles" />
                <button type="submit">Submit</button>
        </div>
        <button type="submit" id="submitOvertime">Submit</button>
    </div>
</div>

</form>

<script>
    // List of Philippine holidays (for example)
    const holidays = [
        '2024-01-01', // New Year's Day
        '2024-04-09', // Araw ng Kagitingan
        '2024-04-10', // Maundy Thursday
        '2024-04-11', // Good Friday
        '2024-05-01', // Labor Day
        '2024-06-12', // Independence Day
        '2024-08-21', // Ninoy Aquino Day
        '2024-08-26', // National Heroes Day
        '2024-11-01', // All Saints' Day
        '2024-11-30', // Bonifacio Day
        '2024-12-25', // Christmas Day
        '2024-12-30'  // Rizal Day
    ];

    const checkbox = document.getElementById('daysOvertimeCheckbox');
    const datePickers = document.getElementById('datePickers');
    const datePickers2 = document.getElementById('datePickers2');
    const startDateInput = document.getElementById('startDate');
    const endDateInput = document.getElementById('endDate');
    const overtimeDateInput = document.getElementById('overtimeDate');

    checkbox.addEventListener('change', function () {
        if (this.checked) {
            datePickers.style.display = 'block';
            datePickers2.style.display = 'none';
        } else {
            datePickers.style.display = 'none';
            datePickers2.style.display = 'block';
            startDateInput.value = '';
            endDateInput.value = '';
        }
    });

    function isHoliday(date) {
        return holidays.includes(date);
    }

    function isWeekend(date) {
        const day = new Date(date).getUTCDay();
        return day === 0 || day === 6; // Sunday is 0 and Saturday is 6
    }

    function disableInvalidDates(input) {
        input.addEventListener('input', function () {
            const dateValue = input.value;
            if (isHoliday(dateValue) || isWeekend(dateValue)) {
                alert('Selected date is either a holiday or a weekend and cannot be selected. Please choose another date.');
                input.value = '';
            }
        });
    }

    disableInvalidDates(startDateInput);
    disableInvalidDates(endDateInput);
    disableInvalidDates(overtimeDateInput);

    // Get current date
    let currentDate = new Date();

    // Get the date exactly two days ahead
    let twoDaysAhead = new Date(currentDate.getTime() + (3 * 24 * 60 * 60 * 1000));

    // Format the dates to YYYY-MM-DD
    let formattedDate = twoDaysAhead.toISOString().slice(0, 10);

    // Set the minimum and maximum attributes for startDate and endDate inputs
    startDateInput.setAttribute("min", formattedDate);
    endDateInput.setAttribute("min", formattedDate);

    // Set the minimum and maximum attributes for overtimeDate input
    overtimeDateInput.setAttribute("min", formattedDate);
</script>

ML_ASP/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}


@if(TempData["failed"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.warning('@TempData["failed"]');
    </script>
}